# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kwidgetsaddons': 'Frameworks/6.24'
    'frameworks/kcompletion': 'Frameworks/6.24'
    'frameworks/kitemviews': 'Frameworks/6.24'
    'frameworks/kxmlgui': 'Frameworks/6.24'
    'frameworks/kiconthemes': 'Frameworks/6.24'
    'frameworks/kcrash': 'Frameworks/6.24'

 - 'on': ['Linux', 'FreeBSD']
   'require':
    'frameworks/kdbusaddons': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
 cppcheck-arguments: '--enable=warning,style,performance --inline-suppr --suppress=passedByValue --suppress=nullPointer'
 tests-run-in-parallel: True
