# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kcompletion' : '@latest-kf6'
    'frameworks/kitemviews' : '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'

- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kdbusaddons': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kcompletion' : '@latest'
    'frameworks/kitemviews' : '@latest'
    'frameworks/kxmlgui': '@latest'
    'frameworks/kcoreaddons': '@latest'

- 'on': ['Linux/Qt6', 'Linux/Qt5']
  'require':
    'sdk/selenium-webdriver-at-spi': '@latest-kf6'

Options:
  require-passing-tests-on: [ 'Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5' ]
  cppcheck-arguments: '--enable=warning,style,performance --inline-suppr --suppress=passedByValue --suppress=nullPointer'
