version = 1
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
SPDX-PackageName = "kdebugsettings"
SPDX-PackageSupplier = "Montel Laurent <montel@kde.org>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/utilities/kdebugsettings"

[[annotations]]
path = ["src/core/autotests/data/**.ini", "src/core/autotests/data/**.ref", "src/core/autotests/data/**.categories", "src/core/autotests/data/**.renamecategories", "data/kde.categories", "data/kde.renamecategories", "data/groups/Full", "Debug", "Ruqola", "logo.png", "readme-build-ftime.txt", "REUSE.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
